version: '3.7'
services:
  Wago-CAA-Runtime:
    env_file:
      - ./${PORTAINER_EDGE_ID}/stack.env
    image: geekychebbi/cc100-codesys:latest
    container_name: "050---wago-caa3-cc-FW27"
    command: "--init"
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp:/tmp
      - /drm:/drm
      - ./${PORTAINER_EDGE_ID}:/home/codesys_root/PlcLogic/Application
    restart: always
