services:
  env-test:
    image: alpine:3.20
    container_name: portainer_context_env_test
    env_file:
      - ./bms_telegraf/${PORTAINER_EDGE_ID}/test.env
    command: ["sh", "-c", "echo \"$TEST_MESSAGE\" && sleep 300"]
    restart: unless-stopped
